name: skilluminaticonfirmed
title: skilluminaticonfirmed
markdown: kramdown
plugins:
    - jekyll-remote-theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
permalink: /writeups/:year/:month/:day/:title
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
